name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: SSHでサーバーに接続してデプロイ
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SAKURA_SERVER_HOST }}
        username: ${{ secrets.SAKURA_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/hiyolabbot
          git pull origin main
          source .venv/bin/activate
          curl -Ls https://astral.sh/uv/install.sh | sh
          mv ~/.cargo/bin/uv .venv/bin/
          .venv/bin/uv pip install --requirements pyproject.toml
          sudo systemctl restart hiyolabbot.service
