name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: セットアップPython
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: 依存関係をインストール
      run: |
        python -m venv .venv
         .venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install .

    - name: テストを実行
      run: |
        . .venv/bin/activate
        python -m unittest discover tests

    - name: デプロイ
      if: success() 
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SAKURA_SERVER_HOST }}
        username: ${{ secrets.SAKURA_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/hiyolabbot
          git pull origin main
          python3 -m venv .venv || true

          ./.venv/bin/pip install --upgrade pip setuptools wheel
          ./.venv/bin/pip install .

          ./.venv/bin/pip list | grep tweepy

          sudo systemctl daemon-reload
          sudo systemctl restart hiyolabbot.service