name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: SSHでサーバーに接続してデプロイ
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/hiyolabbot
          git pull origin main
          if ! command -v uv &> /dev/null; then
            curl -Ls https://astral.sh/uv/install.sh | sh
          fi
          uv pip install --requirements pyproject.toml
          sudo systemctl restart hiyolabbot.service
