name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: SSHでサーバーに接続してデプロイ
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SAKURA_SERVER_HOST }}
        username: ${{ secrets.SAKURA_SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/hiyolabbot
          git pull origin main
          if [ ! -d ".venv" ]; then
            python3 -m venv .venv
          fi
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install .
          sudo systemctl restart hiyolabbot.service
